export const FETCH_WORKSHOPS = 'FETCH_WORKSHOPS';
export const CREATE_WORKSHOP = 'CREATE_WORKSHOP';
export const FETCH_ONE_WORKSHOP = 'FETCH_ONE_WORKSHOP';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
